services:
  postgres:
    image: postgres:16
    container_name: retailops_postgres
    environment:
      POSTGRES_USER: retailops
      POSTGRES_PASSWORD: retailops123
      POSTGRES_DB: retailops
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U retailops"]
      interval: 5s
      timeout: 5s
      retries: 5

  python:
    container_name: retailops_python
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    tty: true
    stdin_open: true




  metabase:
    image: metabase/metabase:latest
    container_name: retailops_metabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  pgdata:
