services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: retail
      POSTGRES_PASSWORD: retail
      POSTGRES_DB: retailops
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  python:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -lc "pip install -U pip && pip install duckdb pandas pyarrow && bash"
    tty: true
    stdin_open: true

volumes:
  pgdata:
